---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 3000, host: 3000}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
suites:
  - name: default
    run_list:
      - recipe[chef-manageiq::default]
